### ISSUE TITLE
User guide on separate website

### ISSUE THREAD

**Issue by ninest** [HavenOfExcellence/mtrac-guide#1]
Apart from the slides, there's also a user guide on the website itself at https://havenofexcellence.me/guide/

I'm working on getting all images from the slides up on this

**Comment by francisyzy** [comment]
Hey, just curious how you are managing the content of the user guide?

From what I see, its all done in .vue files. Was thinking if it was possible to be done in MD so that we can have one centralised docs document that we only update one doc.

IE to say:

MD-> Slides
MD-> Webpage Guide
MD-> Word Doc etc.

**Comment by ninest** [comment]
I'll have to thing of a different solution to support markdown because vue by default doesn't support it

**Comment by ninest** [comment]
I'll look into using this library called MDX which has support for Vue, but I wouldnt rely on it becsuss I'm using Vue 3, and some libraries haven't yet updated.

If it doesn't work, does the AWS server support rewrites?

**Comment by francisyzy** [comment]
Nginx supports serving a different thing from a different /
https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/

**Comment by francisyzy** [comment]
https://stackoverflow.com/questions/27645018/nginx-url-masking-to-a-different-domain for my ref

**Comment by ninest** [comment]
I'm, not sure if the rewrite will allow this, but can you make it that mtrac.ado.sg/guide rewrites to a a site on a different domain?

That way I can independently host the guide on emtrac2-guide.vercel.app, and when people visit mtrac.ado.sg/guide, although they see "mtrac.ado.sg/guide" in the URL bar, they're actually on "emtrac2-guide.vercel.app".

I'm asking because that way we can make and deploy minor changes such as spelling mistakes, images updates without having go on the AWS console and build.

I wonder if this is possible with only Express too? 

- https://www.npmjs.com/package/express-urlrewrite
- https://pavelbucka.com/how-to-rewrite-url-in-express/

**Comment by francisyzy** [comment]
Yup, its kinda working but not really. https://mtrac.ado.sg/guide-test/index.html

**Comment by ninest** [comment]
Are you rewriting to havenofexcellence.github.io?

**Comment by francisyzy** [comment]
Yes but not exactly. https://github.com/HavenOfExcellence/EMTRAC2/commit/7dcdffef2e98eaece1589705429cb8a877c5cabc 

The site is obviously available but somehow github says its not. https://havenofexcellence.github.io/emtrac2-guide/

**Comment by ninest** [comment]
Oh okay.

BTW, what you've done with just markdown files is nice. Do you think doing just this will be okay? If so, we won't have to worry about maintaining another project. Just markdown files

**Comment by francisyzy** [comment]
Yea, i think its okay. I've done it for one of my previous [assignments](https://github.com/francisyzy/CSCAssignment/tree/gh-pages) using a pandoc [template ](https://github.com/tajmone/pandoc-goodies/tree/master/templates/html5/github)to generate easily. Now is just to figure out the fine configs errors etc. Then the entire of next week I'll focus on my main job whereas you have fun typing out documentations :P

**Comment by francisyzy** [comment]
Somehow fighting github isnt working out well. Will try to see if vercel is an easier platform to deal with.
![image](https://user-images.githubusercontent.com/24467184/109412541-8f153180-79e3-11eb-99b6-8f44657940ad.png)


Sike, vercel isnt kind either.

![image](https://user-images.githubusercontent.com/24467184/109412607-ddc2cb80-79e3-11eb-986d-fa6bd2c04f8e.png)


Kinda working?

![image](https://user-images.githubusercontent.com/24467184/109412671-49a53400-79e4-11eb-8374-9d0cf50a558b.png)

![image](https://user-images.githubusercontent.com/24467184/109412719-938e1a00-79e4-11eb-90c1-bc7a8e108b48.png)


Slight issue with Vercel is that to deploy from an github org it requires payment?

![image](https://user-images.githubusercontent.com/24467184/109412707-7a856900-79e4-11eb-96fe-32968286763b.png)

**Comment by ninest** [comment]
https://github.com/HavenOfExcellence/EMTRAC2/blob/dev/nginx_configs/mtrac_ado_sg.conf#L46-L57

If I'm not wrong, you are redirecting this way:

```
/guide-test --> https://havenofexcellence.github.io/emtrac2-guide/
```

Is it possible to do something like

```
/guide-test/$ --> https://havenofexcellence.github.io/emtrac2-guide/$
```
Everything from `/guide-test` is redirected to the guide, including the scripts and styles.

So that means that redirects happen this way:

```
/guide-test/ --> https://havenofexcellence.github.io/emtrac2-guide/
/guide-test/js/script.js --> https://havenofexcellence.github.io/emtrac2-guide/js/script.js
/guide-test/css/style.css --> https://havenofexcellence.github.io/emtrac2-guide/css/style.css
```

**Comment by ninest** [comment]
## Hosting

1. Rewrite mtrac.ado.sg/guide to [mtrac-guide.vercel.app](https://mtrac-guide.vercel.app/)
2. Use sub-subdomain: guide.mtrac.ado.sg
3. If none work, host another node server in EMTRAC

**Comment by francisyzy** [comment]
We should attempt this one last time trying to use github pages instead so that we do not have to deal with another github account to get around vercel's limitation on having to pay $ for a team acc.

**Comment by ninest** [comment]
Okay I'll set next to build to the `docs` directory and have GH pages host from there. I'll see how the base path works

**Comment by ninest** [comment]
Another option: https://github.com/amondnet/vercel-action
It can use the credentials for the person 3TPT Project Team account

**Comment by francisyzy** [comment]
Building is not an issue. What I meant was we do not have to deal with creating another account. IE another GitHub account. If we can distribute the guide using GitHub pages, might as well just distribute from this Repo. Not like having it to be public will cause any issues as the entire website will be public either way right?

> It can use the credentials for the person 3TPT Project Team account

Like we can just login into Vercel using 3TPT Github account and do the building there etc. But why bother if we can get around with not having a 3TPT Github Account if serving from GitHub pages work.

**Comment by ninest** [comment]
I got the site at https://havenofexcellence.github.io/emtrac2-guide/ but I'm not sure why styles aren't loading. I'll look into this

**Comment by ninest** [comment]
https://itnext.io/next-js-app-on-github-pages-768020f2b65e

**Comment by ninest** [comment]
# Worked: https://havenofexcellence.github.io/emtrac2-guide

**Comment by francisyzy** [comment]
Will rename this repo to mtrac-guide so that when we do the link redirection it wouldn't look horrible

**Comment by francisyzy** [comment]
Fixed nginx hosting stuff https://github.com/HavenOfExcellence/EMTRAC2/commit/47d01d551b302fc4133943ec6078b5c6fc3c460f
